//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularjsTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyOrder()
        {
            this.Orderitems = new HashSet<Orderitem>();
        }
    
        public int OrderID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PaymentInfo { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string DeliveryMethod { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryAddress2 { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderitem> Orderitems { get; set; }
    }
}
